### ISSUE TITLE
Release new version with support to stylelint v14 and v15

### ISSUE THREAD

**Issue by bryanjtc** [ierhyna/stylelint-no-indistinguishable-colors#13]
In the latest version, 1.3.2, this package only lists 11, 12, 13 in peer dependencies. Can you create a release with the support for v14? I see the changes to support v14 were made 20 days ago, but they were never published in a new release.

**Comment by TchernyavskyDaniil** [comment]
Not a good idea, but you can add stylelint v14 to `overrides` config for npm or for yarn `resolutions` in `package.json`

**Comment by bryanjtc** [comment]
@ierhyna any update?

**Comment by zandermax** [comment]
I think if we don't hear back by next year, someone will probably need to publish a fork that uses modern versions of dependencies.

**Comment by bryanjtc** [comment]
@axlemax I created a fork and updated everything. Tests pass locally. Here is the pr. https://github.com/ierhyna/stylelint-no-indistinguishable-colors/pull/14
You can set the pr as a resolution in package.json

**Comment by bryanjtc** [comment]
I updated the pr. It now supports v15.
