### ISSUE TITLE
Allow disabling the plugin

### ISSUE THREAD

**Issue by burtek** [ierhyna/stylelint-no-indistinguishable-colors#2]
Please, allow passing `false` to `plugin/stylelint-no-indistinguishable-colors` rule to temporarily disable the plugin without removing the rule completely. This would allow for quick switching on and off during colors or during trying out new color combinations

**Comment by ierhyna** [comment]
Hi @burtek, great idea, thank you. `false` option is added please update the plugin.

**Comment by burtek** [comment]
Thanks :)
