### ISSUE TITLE
npm-warning for "stylelint" peer dependency

### ISSUE THREAD

**Issue by jens-duttke** [ierhyna/stylelint-no-indistinguishable-colors#8]
Right now, npm throws a warning:

> stylelint-no-indistinguishable-colors@1.3.0 requires a peer of stylelint@^11.1.1 but none is installed. You must install peer dependencies yourself.

Currently, stylelint 13.0.0 is the latest version.

I'm using:
```
"stylelint": "13.0.0",
"stylelint-no-indistinguishable-colors": "1.3.0",
```

**Comment by jeffrson** [comment]
Unfortunately this is broken since last november when stylelint 12.0.0 was released.

We might end with impossible peerDependencies (package1 might specify "^11.1.1" while  package2 has "^12.0.0").

Please check whether the following works and update to:

```
"peerDependencies": {
    "stylelint": ^11.1.1 || ^12.0.0 || ^13.0.0"
}
```
